### ISSUE TITLE
Hidden Tabs on EzPageHeader Subnav

### ISSUE THREAD

**Issue by jbelang** [ezcater/recipe#143]
There are often scenarios where we only want to show a subset of the subnav tabs to a particular user. For instance, different users may have permission to view different features, and so will see different sets of tabs corresponding to those features.

Related to this is the idea that, if a user only has one visible tab, we sometimes want to hide the subnav altogether.

We can get around both of these problems by checking "visibility" while building up the tabs array, but it could be very convenient to have the notion of "visibility" on a tab.

**Comment by CraigCav** [comment]
I'm going to close this off, as we're unlikely to build it given there is a clear alternative.
