### ISSUE TITLE
Card Loading States

### ISSUE THREAD

**Issue by dave-ezcater** [ezcater/recipe#198]
Implement three styles of loading state:

1. For Cards, and Tables that fill a card, that are loading for the first time, show a skeleton title and a spinner horizontally and vertically centered on the card. Set a height of 140px while the card is loading.
2. For tables with pagination, or tables with filters where the new set of rows is being loaded, put an 80% opacity white overlay on the existing <tbody> and a spinner horizontally and vertically centered over that.
3. For existing cards that are being loaded, put an 80% opacity white overlay over the existing content and a spinner horizontally and vertically centered over that. 

<img width="821" alt="Screen Shot 2019-08-08 at 5 18 20 PM" src="https://user-images.githubusercontent.com/39057183/62738542-8d9aa780-ba00-11e9-8f86-ba2504282bbf.png">

**Comment by noranda** [comment]
Closing issue. This feature will need to be reviewed by our current designers to determine if it's needed and/or a good fit for Recipe.

**Comment by noranda** [comment]
Closed as not planned.
