### ISSUE TITLE
Using the date picker component in EzTable causes overlapping

### ISSUE THREAD

**Issue by stacy-wells** [ezcater/recipe#200]
Using the EzField with a type of date inside an EzTable causes the date picker to be cutoff.

An example of this can be seen [here](https://pasta.staging-ezcater.com/brand/400/caterers/temporary-closures/edit).

<img width="901" alt="Screen Shot 2019-08-14 at 1 08 05 PM" src="https://user-images.githubusercontent.com/11218638/63097254-f53f7e00-bf3d-11e9-8aa8-56be9b49d3a8.png">

**Comment by CraigCav** [comment]
This should have been fixed as part of #420.
