### ISSUE TITLE
Allow EzTable to be set to a fixed height

### ISSUE THREAD

**Issue by jaeger401** [ezcater/recipe#230]
Once upon a time, we wanted to add a fixed-height table to PaSTA. There was [much consternation](https://github.com/ezcater/pasta-react/pull/613#issuecomment-527616471). 

We ended up redesigning with pagination, but that's a suboptimal user experience. It would be peachy if instead we could have specified a height constraint in EzTable.

**Comment by noranda** [comment]
Closing this issue. This `EzTable` feature is not currently needed and would require designer input. In addition, `EzTable` will be undergoing a redesign/refactor in the near future, which may end up addressing this issue.
