### ISSUE TITLE
Docs for EzStatus don't explain when to use the different sizes

### ISSUE THREAD

**Issue by ayip8** [ezcater/recipe#235]
**Describe the bug**

We should provide guidance about when to use the different sizes of EzStatus.

**To Reproduce**

View the doc page for EzStatus https://ezcater.github.io/recipe/components/ez-status

**Expected behavior**

There should be clear guidance about when to use one size vs. the other.

**Screenshots**

![image](https://user-images.githubusercontent.com/16192761/67229468-5a659300-f409-11e9-83c5-b8545e0d65ee.png)

**Additional context**

**Comment by noranda** [comment]
Closing this issue. `EzStatus` is now deprecated. See `EzChip` [status variants](https://ezcater.github.io/recipe/components/ez-chip#status). Sizes used will depend on the design/use case of the implementation and is not Recipe-specific.
