### ISSUE TITLE
Disabled EzButtons && Accessibility

### ISSUE THREAD

**Issue by paulmthiebauth** [ezcater/recipe#251]
While working on a [recent PR](https://github.com/ezcater/recipe/pull/246) Craig and I talked about some underlying issues with disabled buttons and accessibility. Lately we’ve started to more commonly use a pattern of wrapping a disabled EzButton in an EzTooltip to describe why the button is disabled.  In recipes current state, a disabled button wont be picked up when tabbing through elements on the page so the Tooltip will never be utilized by tools that help with accessibility such as screen readers, which is obviously a problem. Tackling this issue most likely warrants some further discussion so that we can think about a broader pattern that we may want to use when disabling elements.

One possible solution we had discussed while working through this was to disable the `onClick` so that nothing happens when the button is used instead of setting it to `disabled`. The button would then be able to be focused but would function as if it were disabled in the sense that no action would be taken if the button was clicked. This is just one example and there are potentially other solutions to the underlying problem that we should discuss when there is time.

**Comment by noranda** [comment]
`EzButton` and `EzTooltip` will be undergoing refactors soon that should fix this issue with MUI's implementations, which [advises](https://mui.com/material-ui/react-tooltip/#disabled-elements) to simply add a wrapper element, such as a span, to make the tooltip activate on normal events like hover. Closing issue.
