### ISSUE TITLE
EzModal - no scrolling or viewing the bottom row of buttons in IE11

### ISSUE THREAD

**Issue by klaw772** [ezcater/recipe#260]
**Describe the bug**

In IE11, when an ezModal is resized so that the full size of the modal is not being shown, the body of the modal cuts off and is not scroll-able. Additionally, the bottom row of buttons is cut off and cannot be accessed.

**To Reproduce**

1. Open up an EzModal in IE11
2. Resize the current page such that the size of the body of the modal decreases, e.g. by zooming in or decreasing the size of the browser window

**Expected behavior**

When resizing an EzModal, the body of the modal should be scroll-able, and the bottom row of buttons should be consistently visible.

**Screenshots**

![ezmodal resizing](https://user-images.githubusercontent.com/28101298/70356998-c417f000-1843-11ea-9ec9-254a9c2b6108.gif)

**Comment by noranda** [comment]
Closing issue. We no longer support IE11. Verified this is not an issue in all modern supported browsers.
