### ISSUE TITLE
Documentation request: Document the list of props for each component

### ISSUE THREAD

**Issue by kevinmook** [ezcater/recipe#322]
Recipe is amazing and incredibly helpful, but it's really difficult to know what props are available on any given component, what they do, and how they're intended to be used. Right now components have a lot of examples and there are great content guidelines, but there's no at-a-glance list of props/options.

It would be really helpful if at the top of each component's documentation page, every prop for that component was listed with a description, default value (if any), if it's optional or required, and perhaps a note about how it's intended to be used.

**Comment by noranda** [comment]
Closing this issue. We recently introduced a `PropsTable` component that we started using for new components in Recipe (ex. see [`EzChip`](https://ezcater.github.io/recipe/components/ez-chip#props)). We are also planning to move to Storybook Docs, which automates this. Stay tuned!
