### ISSUE TITLE
Accessibility issue: line-length too wide

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#347]
## Describe the issue

Card content (in particular form fields, but also paragraph content), are not width constrained today and stretch to fill the available space.

This causes issue one some layouts; text readability is affected when the line-length is more than 70 characters (UX guidelines tend to recommended 70 characters for desktop, 40-50 on small mobile phone size screens).

Other factors that influence the ideal line-length:

- Typeface
- Font size
- Letter spacing*
- Word spacing*
- Foreground / background contrast
- Measure
- Leading (space between lines)

## Screenshots

Full width page:
![image](https://user-images.githubusercontent.com/109814/80737374-67162280-8ae1-11ea-9bbb-0c0255142528.png)

Centered page (fields are still very wide):
![image](https://user-images.githubusercontent.com/109814/80737407-7301e480-8ae1-11ea-95f3-7b068ca81c6d.png)

## Additional context

Related to #346

**Comment by noranda** [comment]
Closing stale issue as not planned. Layout approaches will need to be reviewed by design. Added to [ideas](https://github.com/ezcater/recipe/discussions/871) to track.
