### ISSUE TITLE
Bug: EzSelect dropdowns flickering on IE11

### ISSUE THREAD

**Issue by paulmthiebauth** [ezcater/recipe#367]
## Describe the bug
After upgrading to Emotion 10 and Recipe 10.3.0 in EzManage I noticed a bug with EzSelect dropdowns when using IE11. The functionality is still intact in the sense that a user can (with a little extra effort) select the option they want from the dropdown and submit the form, however, the UX is less than ideal. When interacting with the menu, the element appears to flicker and ends up being pegged to the top left of the screen from time to time. 

## Steps To Reproduce
The instance I've been working with specifically is on the Bulk Edit Operating Schedules page in EzManage. The URL for that page is: https://ezmanage.staging-ezcater.com/settings/stores/operating-hours/edit
(This is all to be done in IE11!)
1. Log into EzM as a brand admin (my go-to is Bertuccis https://www.staging-ezcater.com/admin_contacts/show/371216)
2. Go to Settings on the Nav bar and select a few stores + click Edit Selected
3. Proceed to the Operating Hours page
4. Interact with any of the dropdowns (the time dropdowns will be the easiest to replicate with)

Link to code example:
https://github.com/ezcater/ezcater-ezmanage-ui/blob/master/src/components/OperatingSchedulesForm/TimeOfDayDropDown.js

This is the code that represents the dropdowns that's are being used within the Operating hours page (for the open and close at specifically, though other dropdowns are also wacky)

## Current behavior
See "Describe the bug"

## Expected behavior
It would be expected that the dropdown menus do not flicker and are easy to interact with when using IE11

## Screenshots
![IE11XSMALL](https://user-images.githubusercontent.com/9626789/82921986-0bf01800-9f47-11ea-8292-173dbc436f43.gif)

## Additional context
- I have not done a version by version comparison to see if this was introduced in a specific version but that may be worth doing. Note that we'll have to test that out via Dev1 as were having issues (that were introduced prior to Emo10 and Recipe 10.3.0) when using IE11 locally to view EzManage (a separate ticket has been logged in the EZMNG teams board)

**Comment by CraigCav** [comment]
Closing this as unreproducible. If this is still an issue, please feel free to reopen and we can coordinate an effort to reproduce this outside of a downstream application.
