### ISSUE TITLE
Support validating acknowledgement checkbox

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#376]
**Is your feature request related to a problem? Please describe.**

EzField supports `error` and `touched` props to support giving the user feedback on invalid input.

It's common for users to be required to confirm/acknowledge that they have read/agreed to terms before being allowed to proceed, and therefore it is likely that we need to support highlighting the input if left unchecked. 

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Some good questions to answer are:

- When should this component be used?
- When shouldn’t it be used? For those cases, is there an alternative component you’d recommend (and why do you recommend it)?
- When should each variation of the component be used?
- What are guidelines for the content that could go into this component?
- Are there limitations/restrictions on what it can handle?
- Is anything not going into this first version? What did you exclude and what was the reasoning behind that?

**Design Mockups**

Add any other context and screenshots about the feature request here.

**Comment by noranda** [comment]
`EzCheckbox` was recently refactored to support theme colors (scheduled for release in v16), which will allow users to use color to assist with validation. Closing issue as completed.
