### ISSUE TITLE
Documentation: Clearer prop descriptions on EzTable docs.

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#389]
The docs for EzTable don't describe the `columns` or `items` props very clearly. In particular, `columns` accepts a iterable list of objects that can have `heading`, `accessor`, `key`, `component`, `sortable` properties, but we currently only describe `component` and `sortable`.

**Comment by noranda** [comment]
Closing as not planned. We are moving to Storybook Docs soon which has automatic props documentation support.
