### ISSUE TITLE
Footer buttons

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#393]
**Is your feature request related to a problem? Please describe.**

Not sure of a good name for this component/variation. Today, EzCardFooter (part of EzCard) and the `expandable` option for EzTimeline use a specific style for their buttons.

We should consider making this a first-class citizen of Recipe so that this style can be applied as-needed in downstream apps.

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Some good questions to answer are:

- When should this component be used?
- When shouldn’t it be used? For those cases, is there an alternative component you’d recommend (and why do you recommend it)?
- When should each variation of the component be used?
- What are guidelines for the content that could go into this component?
- Are there limitations/restrictions on what it can handle?
- Is anything not going into this first version? What did you exclude and what was the reasoning behind that?

**Design Mockups**

See #195 for the timeline design (and #390 for the implementation).

![image](https://user-images.githubusercontent.com/109814/87172002-824f9c00-c2a1-11ea-9908-57d13e56afac.png)

See [abstract](https://share.goabstract.com/447553f8-0634-4e58-b262-fe1455e6d359?mode=design&sha=b7ab547f1fca1d01d3593f7db15f1e0193f35259) for the EzCard footer design.

![image](https://user-images.githubusercontent.com/109814/87171961-719f2600-c2a1-11ea-9bc2-80faf178ad9b.png)

**Comment by noranda** [comment]
Closing as not planned. `EzCardFooter` is no longer a component in Recipe.
