### ISSUE TITLE
Consider API for generating semantic lists with EzLayout

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#394]
**Is your feature request related to a problem? Please describe.**

I want to use semantic HTML for lists, but I want more control of the layout. 

See [this PR comment](https://github.com/ezcater/recipe/pull/390/files#r452929061) on the implementation of timeline.

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Some good questions to answer are:

- When should this component be used?
- When shouldn’t it be used? For those cases, is there an alternative component you’d recommend (and why do you recommend it)?
- When should each variation of the component be used?
- What are guidelines for the content that could go into this component?
- Are there limitations/restrictions on what it can handle?
- Is anything not going into this first version? What did you exclude and what was the reasoning behind that?

**Design Mockups**

Add any other context and screenshots about the feature request here.

**Comment by noranda** [comment]
Closing as not planned. Will need designer input. Added to [Recipe Ideas](https://github.com/ezcater/recipe/discussions/871) discussion.
