### ISSUE TITLE
Icons in Recipe?

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#40]
We'd like to hear more about what we expect Recipe to provide. 

So far we’ve heard:

1. need more icons
2. inconsistent alignment
3. inconsistent sizing and support for color
4. “not very good” :slightly_smiling_face:

What i’d expect us to be doing is standardizing on some icon implementation guidelines (common base size, common alignment, ability to scale with font size, ability to be styled with color)

**Comment by noranda** [comment]
Closing this issue. See [EzIcon](https://ezcater.github.io/recipe/components/ez-icon).
