### ISSUE TITLE
Bug: Checkbox labels aren't rendered

### ISSUE THREAD

**Issue by kevinmook** [ezcater/recipe#404]
## Describe the bug

The "label" prop passed in to a checkbox isn't rendered (unless the "acknowledgement" prop is set to true).

## Steps To Reproduce

1. Check out the basic checkbox here: https://ezcater.github.io/recipe/components/ez-checkbox#basic-checkbox - the label isn't rendered

## Current behavior

The label prop isn't rendered

## Expected behavior

The label prop should be rendered

## Additional context

Once fixed, I'd expect this to be classified as a breaking change as all existing checkboxes will need to have their existing labels updated / replaced.

**Comment by noranda** [comment]
[v16](https://github.com/ezcater/recipe/blob/v16/packages/recipe/src/components/EzCheckbox/EzCheckbox.md#checkbox-labels) includes a newly redesigned and refactored `EzCheckbox` that fixes this issue. Closing.
