### ISSUE TITLE
Bug: In an EzLayout, EzCheckboxes can get cut off if their parent has overflow: hidden and aren't properly aligned

### ISSUE THREAD

**Issue by kevinmook** [ezcater/recipe#405]
## Describe the bug

An EzCheckbox can get cut off if its parent has overflow: hidden. They also are slightly misaligned with text next to them.

## Steps To Reproduce

1. Go to https://ezcater.github.io/recipe/components/ez-checkbox#basic-checkbox
2. Update the example like so:

```
() => {
  const [checked, setChecked] = React.useState(true);
  return (
    <div style={{overflow: "hidden"}}>
      <EzLayout>
        <EzCheckbox label="Basic checkbox" onChange={() => setChecked(!checked)} checked={checked} />
        <span>Basic checkbox</span>
      </EzLayout>
    </div>
  );
};
```

## Current behavior

The checkbox is cut off and slightly misaligned:
<img width="897" alt="Screen Shot 2020-08-04 at 12 26 19 PM" src="https://user-images.githubusercontent.com/832755/89319157-bd00e600-d64d-11ea-92e1-7dd91e0c42be.png">

## Expected behavior

The checkbox shouldn't be cut off and should be aligned with the text. Wrapping the checkbox in a span seems to work, but is probably not the ideal solution:
<img width="887" alt="Screen Shot 2020-08-04 at 12 30 19 PM" src="https://user-images.githubusercontent.com/832755/89319595-56c89300-d64e-11ea-9aa3-6f4bfc3294d1.png">

**Comment by CraigCav** [comment]
This is not currently an issue [demo](https://ezcater.github.io/recipe/playroom/?code=N4Igxg9gJgpiBcIA8BRAXgGQIYE8IFcAXAPgB0A7AAktTQGEALGMAawCMIAPSgGyzZg8AvKRAAhLAGcAlmEpgmrDp1HzFLGFCHBCAJ3wwAvpQD0ZKjUkAHLOWISZchc3ZckJ67fPv02PEWIQQyA).

We'll still try to tackle #404 separately.
