### ISSUE TITLE
Bug: findIndex polyfill required for IE11

### ISSUE THREAD

**Issue by kevinmook** [ezcater/recipe#411]
## Describe the bug
Recipe 10.6.0 uses findIndex in a few places, which [isn't available on IE11 without a polyfill](https://caniuse.com/#search=findIndex). https://ezcater.github.io/recipe/guides/getting-started#browser-support doesn't seem to include findIndex among the required polyfills.

The fix could be to remove references to findIndex in Recipe, directly polyfill findIndex, or to update the documentation to require a findIndex polyfill.

## Steps To Reproduce

1. In a project without a "findIndex" polyfill, make a component with a `<EzField type="select" {...} />`
2. Load up browserstack with IE11 and view the component

Specifically I got an error in IE11 when rendering an EzField ( https://sentry.io/organizations/ezcater/issues/1835715027/ ) but it looks like there are other components that reference findIndex as well.

## Current behavior
The component throws an error and the error boundary is rendered.

## Expected behavior
The EzField renders!

## Additional context
Sentry with the error: https://sentry.io/organizations/ezcater/issues/1835715027/

**Comment by CraigCav** [comment]
This was addressed in PR #502 and released in [v11.4.0](https://ezcater.github.io/recipe/changelog#1140---2021-02-22).
