### ISSUE TITLE
Totals row in Table

### ISSUE THREAD

**Issue by johnhemminger** [ezcater/recipe#421]
**Is your feature request related to a problem? Please describe.**

Yes, in relation to the RAF page we are hoping to have a row at the bottom of the referrals table to help the customer understand the lifetime value of referring friends to ezCater (i.e., the total amount of ezRewards dollars they have earned from referrals). Users would benefit from knowing how many of their ezRewards dollars come from referrals and it can potentially incentivize them to refer MORE people if they see how bountiful the returns are.

**Describe the solution you'd like**

> When should this component be used? 

This component should be used, initially, in the RAF page Referrals table but honestly I think it can be useful in other current or future scenarios where total numbers are of value.

> When shouldn’t it be used? 

For those cases, is there an alternative component you’d recommend (and why do you recommend it)? Can't think of anything, other than don't use it as a default

> When should each variation of the component be used? 

No variations at this moment.

> What are guidelines for the content that could go into this component? 

Content should be numeric, otherwise it won't make any sense.

> Are there limitations/restrictions on what it can handle? 

Not sure

> Is anything not going into this first version? What did you exclude and what was the reasoning behind that? 

Nope.

**Design Mockups**

Add any other context and screenshots about the feature request here.
https://ezcater.invisionapp.com/console/share/CG1J52UQBS/480863946

**Comment by noranda** [comment]
Closing stale issue as not planned. This feature will need to be reviewed by our current designers to determine if it's needed and/or a good fit for Recipe.
