### ISSUE TITLE
Contextual Styling

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#425]
**Is your feature request related to a problem? Please describe.**

As part of the "Recipe everywhere initiative, Recipe will require updates in order to support product-specific branding. Marketplace as a whole is geared towards marketing and conversion and in turn necessitates additional UI patterns and styles that draw focus to a given Call To Action (CTA).

[Hero banners](https://en.wikipedia.org/wiki/Hero_image) are a common pattern in marketplace, particularly in landing pages, but also in supplementary marketing content. Hero banners present the page's most important content, layered onto a vibrant visual element, usually a photo or colorful background image, to draw focus. Photos are quite dynamic; they can have light areas and dark areas. This presents an issue as text not only needs a consistent contrast to be legible (and accessible), but also to ensure the CTA isn't overlooked. Using a fixed heading text color and button color (as we do in Recipe today) would severely limit our ability to create captivating CTAs, as it would limit our background choices to only include a set providing sufficient contrast to our text. While this issue particularly affects Hero banners, it's also prevalent in other marketing patterns like alternating background sections or when overlaying text within cards and modals.

A corollary to the added emphasis on CTAs, is that to achieve an appropriate visual hierarchy, secondary and tertiary information should be deliberately de-emphasized as not to draw focus away from the most important page content. This can mean that secondary and tertiary content may need to have reduced contrast, a lighter font weight or smaller size.

A core consideration to make, especially in light our company branding update, is that allowing components to be individually overridable on a case-per-case basis in order to facilitate an appropriate visual hierarchy can be problematic. It will be difficult to apply overrides uniformly and ultimately it will be harder to retain consistency as our products evolve. Instead we should try to leverage the tone and context of the page hierarchy to automatically and consistently apply styles.

**Describe the solution you'd like**

At its core, the solution should allow for scenarios like this:

Hero with darker background e.g. the [ezcater brand](https://ezcater.atlassian.net/wiki/spaces/MAR/pages/1131643470/The+new+ezCater+brand+identity) Ez green ![#00B373](https://via.placeholder.com/15/00B373/000000?text=+)
```jsx
  <EzHero tone="dark">
    <EzHeading>Should be white text</EzHeading>
  </EzHero>
```

Hero with light background e.g. the [ezcater brand](https://ezcater.atlassian.net/wiki/spaces/MAR/pages/1131643470/The+new+ezCater+brand+identity) vanilla frosting ![#F9FAE4](https://via.placeholder.com/15/F9FAE4/000000?text=+)
```jsx
  <EzHero tone="light">
    <EzHeading>Should be dark text</EzHeading>
  </EzHero>
```

The `EzHeading` component shouldn't need to be told to render with a specific color, but will instead infer an accessible brand approved color to apply as a direct result of being a descendant of the styled ancestor. We'll likely want to restrict the set of "tones" at least to start with (or have the tone and contrasting color fixed at a theme-level). 

Similarly, primary buttons that would typically render as blue when used with a page header might automatically be de-emphasized when used within a table:

| before             |  after  |
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/109814/94312595-2f55be80-ff4b-11ea-9565-50feadd235fa.png) | ![image](https://user-images.githubusercontent.com/109814/94312626-3d0b4400-ff4b-11ea-9abb-f38746dfee05.png)

This could be achieved in a number of ways:

1. Using a [CSS descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator)
1. Using emotion's (somewhat flakey) support for [nested component selectors](https://emotion.sh/docs/nested)
1. Using React context (the Braid design system has a [pretty good example of doing something similar to this](https://seek-oss.github.io/braid-design-system/components/BackgroundProvider))
1. Some other way?

**Comment by noranda** [comment]
We just released [Recipe v14](https://github.com/ezcater/recipe/releases/tag/v14.0.0) in PR https://github.com/ezcater/recipe/pull/803, which adds theming support! This includes [documentation](http://localhost:8000/guides/getting-started/#recipe-themes) about theming, describing how to extend themes and use theme properties like color in downstream apps. A list of our supported theme properties can be found on our new [Theming](http://localhost:8000/guides/theming) page. 

These new emotion themes let us take advantage of the [default MUI theme](https://mui.com/customization/default-theme/), which provides defined theme properties for different contexts (for example, `primary`, `secondary`, `warning`, `info`, `alert`, etc). For each context, we can provide colors for `main`, `light`, `dark`, and `contrastText`. This allows us to do a lot of what you discuss here, including have the theme itself provide appropriate colors for components depending on context. In `ezTheme`, we define theme colors (found in `ezPalette`) for each.
