### ISSUE TITLE
Updated color palette 

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#426]
**Is your feature request related to a problem? Please describe.**

As part of the "Recipe everywhere initiative, Recipe will require updates in order to support product-specific branding. 

### Grays

Recipe's grays are currently tinted with a blue-ish hue. Non-tinted grays can work alongside any brand color and don’t draw a user’s attention away from the main focus on a color manipulation task or workflow.

We may wish to revisit our choice of grays as we revise the color palette.

### Semantic Colors

Semantic colors have assigned meanings and are used consistently throughout Recipe to set expectations of meaning for users.

Today, Recipe uses the following Semantic Colors"

**Informative**

Guidance & advice. Functional, calm and non urgent.

![#1e70bf](https://via.placeholder.com/15/1e70bf/000000?text=+) ![#3e90d6](https://via.placeholder.com/15/3e90d6/000000?text=+) ![#c1def4](https://via.placeholder.com/15/c1def4/000000?text=+) ![#ebf7ff](https://via.placeholder.com/15/ebf7ff/000000?text=+)  

**Negative**

High Risk or Urgent messages. Errors or Failures. Negative trends.

![#ae4d4d](https://via.placeholder.com/15/ae4d4d/000000?text=+) ![#ec5353](https://via.placeholder.com/15/ec5353/000000?text=+) ![#f7c1c1](https://via.placeholder.com/15/f7c1c1/000000?text=+) ![#fdefef](https://via.placeholder.com/15/fdefef/000000?text=+)  

**Notice**
Notification that something is happening or mid-way through a process. Low risk/urgency, pending or draft.

![#926a00](https://via.placeholder.com/15/926a00/000000?text=+) ![#e9a801](https://via.placeholder.com/15/e9a801/000000?text=+) ![#f4d689](https://via.placeholder.com/15/f4d689/000000?text=+) ![#fcf6e5](https://via.placeholder.com/15/fcf6e5/000000?text=+)  

**Positive**

Success or completion. Positive trend. 

![#609b3b](https://via.placeholder.com/15/609b3b/000000?text=+) ![#88bb40](https://via.placeholder.com/15/88bb40/000000?text=+) ![#c7dfa7](https://via.placeholder.com/15/c7dfa7/000000?text=+) ![#f3f8eb](https://via.placeholder.com/15/f3f8eb/000000?text=+)  

### Static Colors

Some design systems use static colors (i.e. colors that are consistent across all themes). Typically these colors are used for:

- Focus ring
- Error message background/border

The general idea is that static colors are used for backgrounds and are paired with white text.

### Dark mode

It's not uncommon for color palettes to include a "dark mode" for reducing eye strain. That being said, dark mode doesn't seem like a "must have" feature for any of our current products.

**Comment by noranda** [comment]
We just released [Recipe v14](https://github.com/ezcater/recipe/releases/tag/v14.0.0) in PR https://github.com/ezcater/recipe/pull/803, which adds theming support! A list of all our supported theme properties can be found on our new [Theming](http://localhost:8000/guides/theming) page. Recipe's supported color palette is designer-curated and may evolve in the future.

Thanks!
