### ISSUE TITLE
Bug: Incrementing IDs break SSR

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#432]
## Describe the bug

Reported by the store team: https://ezcater.slack.com/archives/CBC9DMGP5/p1602081102027700

> the incrementing IDs break when using SSR (the ID is global and thus shared across all requests, but the client has a fresh one every time). I noticed this in store react but this is a good time to mention it!

## Steps To Reproduce

1.
2.

Link to code example:

**Comment by noranda** [comment]
Closed as no longer an issue per @pgrippi.
