### ISSUE TITLE
Group Inputs (as seen on Start New Order)

### ISSUE THREAD

**Issue by jbelang** [ezcater/recipe#438]
**Is your feature request related to a problem? Please describe.**

A key component on the Start New Order page is a grouped event details input that accepts address, date, time, and headcount. Due to not having accessible, reusable, easy to work with date/time pickers available outside of Recipe, we hacked the input together using EzFields.

**Describe the solution you'd like**

As this concept becomes further used and even more central to our designs, we would benefit from smoothing out the rough edges and turning it into a first class citizen. There are also concerns about giving it more carefully considered mobile behavior. 

**Design Mockups**

We're currently hacking together Recipe inputs to make this:
**Desktop**
![image](https://user-images.githubusercontent.com/6944977/96312799-564b6180-0fda-11eb-9e6d-599562147882.png)

**Mobile**
![image](https://user-images.githubusercontent.com/6944977/96312952-a5919200-0fda-11eb-8fa1-0ddb928e3b53.png)

We will soon want to reskin that to look like this:
![image](https://user-images.githubusercontent.com/6944977/96312817-62372380-0fda-11eb-925c-885f1e1f9e59.png)

**Comment by noranda** [comment]
Closing stale issue. Related to [Recipe Request DF-373](https://ezcater.atlassian.net/browse/DF-373). Will need design input.
