### ISSUE TITLE
Links with Icons

### ISSUE THREAD

**Issue by jbelang** [ezcater/recipe#441]
**Is your feature request related to a problem? Please describe.**

We have some designs that call for regular blue links that include icons as part of the link. This is something already supported in tertiary buttons, and it would make sense for these things to be able to behave in similar ways.

**Describe the solution you'd like**

A variation on link that could be used when we want the link text to include an icon.

**Design Mockups**

An example:
![image](https://user-images.githubusercontent.com/6944977/96314405-f655ba80-0fdb-11eb-86e7-94b028253b35.png)

**Comment by noranda** [comment]
Closing stale issue as not planned. This would need a new design and current use case.
