### ISSUE TITLE
Bug: Error Message positioning / overlapping with popover

### ISSUE THREAD

**Issue by onocy** [ezcater/recipe#471]
## Describe the bug

With small inputs, we would like it if we could not specify an error message for the tooltip on the input. Usually with these small inputs (for the headcount input of our package related form) we just want the surrounding styles (red border, red label, and error icon) but want the message to be a separate element, usually because the message is hidden by a dropdown that appears when the input is touched. 

We have solved this by using our own styling for the error state, but it would be helpful if we could tell the component that it doesn't need to render an error message tooltip. 

## Steps To Reproduce

1.
2.

Link to code example:

https://github.com/ezcater/store-react/pull/3528

## Screenshots

![Screen Shot 2020-12-16 at 3 43 10 PM](https://user-images.githubusercontent.com/11084873/102404727-155dd200-3fb6-11eb-8958-93a30ced9bc3.png)
![Screen Shot 2020-12-16 at 9 24 47 AM](https://user-images.githubusercontent.com/11084873/102404743-1a228600-3fb6-11eb-8c8e-305234c4de0a.png)

**Comment by noranda** [comment]
Closing as not planned. No longer needed per @pgrippi. Added to [ideas](https://github.com/ezcater/recipe/discussions/871).
