### ISSUE TITLE
Bug: EzLayout horizontal spacing between cards is not applied on IE11

### ISSUE THREAD

**Issue by fenjiot** [ezcater/recipe#480]
## Describe the bug
On IE11, expected horizontal margins are missing when using EzLayout to layout child components.

## Steps To Reproduce

1. Use EzLayout to layout at least 2 cards
2. View output with IE11

Code to setup a basic example:
```
<EzLayout layout="tile" columns={3}>
      <Placeholder height={48} />
      <Placeholder height={48} />
      <Placeholder height={48} />
      <Placeholder height={48} />
      <Placeholder height={48} />
    </EzLayout>
```

This is the case with a bunch of components in `store-react`, such as 
- EzRewards components: [EnrolledContent](https://github.com/ezcater/store-react/blob/master/src/pages/EzRewards/components/EnrolledContent.js#L77-L92), [EarnMorePoints](https://github.com/ezcater/store-react/blob/master/src/pages/EzRewards/components/EarnMorePoints.js#L118-L149)  
- ReferAFriend component: [HowItWorks](https://github.com/ezcater/store-react/blob/master/src/pages/ReferAFriend/components/HowItWorks.js#L68-L102)

## Current behavior
When rendered on IE11, horizontal margins are missing

## Expected behavior
Expect horizontal margins to be present like with other browsers.

### EzRewards components viewed on Chrome
Shows [EnrolledContent](https://github.com/ezcater/store-react/blob/master/src/pages/EzRewards/components/EnrolledContent.js#L77-L92) margins applied as expected on Chrome
<img width="1012" alt="Screen Shot 2021-01-13 at 1 32 04 PM" src="https://user-images.githubusercontent.com/2309768/104496944-a6b96780-55a7-11eb-93dc-68771ef2d651.png">

Shows [EarnMorePoints](https://github.com/ezcater/store-react/blob/master/src/pages/EzRewards/components/EarnMorePoints.js#L118-L149) margins applied as expected on Chrome
<img width="1494" alt="Screen Shot 2021-01-13 at 1 06 39 PM" src="https://user-images.githubusercontent.com/2309768/104497108-dcf6e700-55a7-11eb-96ff-9a5028b29005.png">

### EzRewards viewed on IE11 (via BrowserStack)
Shows [EarnMorePoints](https://github.com/ezcater/store-react/blob/master/src/pages/EzRewards/components/EarnMorePoints.js#L118-L149) margins missing on IE11
<img width="1424" alt="Screen Shot 2021-01-13 at 1 21 12 PM" src="https://user-images.githubusercontent.com/2309768/104497233-09126800-55a8-11eb-81e2-1c21b8b7adb7.png">

With red border (added for emphasis)
<img width="1541" alt="Screen Shot 2021-01-13 at 1 18 39 PM" src="https://user-images.githubusercontent.com/2309768/104497173-f13ae400-55a7-11eb-88c4-13e881756a0c.png">

## Additional context

Interestingly enough, vertical spacing seems to work fine.

**Comment by CraigCav** [comment]
Going to close this issue as I believe the only outstanding IE11 issue for layout is already covered by issue #650.
