### ISSUE TITLE
Bug: Undefined CSS variables causing console warnings in IE11

### ISSUE THREAD

**Issue by maggiedbaker** [ezcater/recipe#487]
## Describe the bug
Some CSS variables used in Recipe are not defined anywhere. The [css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) outputs many warnings in IE11:

![Screen Shot 2021-01-19 at 12 53 02 PM](https://user-images.githubusercontent.com/4922450/105451178-4d050d00-5c39-11eb-8763-ab58e531aee1.png)

For example `EzButton.styles.tsx`  uses these vars, which are not defined anywhere. 

```
--recipe-button-tertiary-background-color
--recipe-button-tertiary-background-color-down
--recipe-button-tertiary-background-color-focus
--recipe-button-tertiary-background-color-hover
--recipe-button-tertiary-border-color
--recipe-button-tertiary-border-color-down
--recipe-button-tertiary-border-color-hover
```

However, some of these styles are extension points for theming that aren't necessarily used. For example, tertiary buttons don't have a background color today (and are styled more like links), but in the near future, they're likely to have at least a hover/focus/active color. By having the variable in place, we can add the style with a CSS variable, within the theme style sheet, without having to touch the component itself.

Although the warnings are harmless and only in browsers that use the polyfill, we should define some browser-based default variables (initial or inherit or something similar) to avoid these warnings.

## Steps To Reproduce

1. Navigate to ezCater.com on IE11
2. View the developer console.

**Comment by noranda** [comment]
Closing this issue. We no longer support IE11 and are working on removing stitches, which use these variables.
