### ISSUE TITLE
Feature Request: Expose EzCalendar as a public component

### ISSUE THREAD

**Issue by pgrippi** [ezcater/recipe#499]
This was something I came across when rebuilding the EventBar in store-next

The EventBar has an inline, full calendar that users can get to if their order date is further than 5 days away. It looks like this:

<img width="381" alt="Screen Shot 2021-02-08 at 3 54 12 PM" src="https://user-images.githubusercontent.com/1180841/107280203-016aa580-6a26-11eb-9167-6886dafd2077.png">

In ez-rails this component is written using `Pikaday`. In store-react it was rewritten to use `react-datepicker` (which was already in the project).

`react-datepicker` meets our basic needs, but it uses popper.js 1.x. It is also accessible (or at least I see `aria-label` on the individual day cells), but the labels are different from what EzCalendar uses.

I took a look at EzCalendar and it appears that it meets all of the needs of the EventBar:

* It takes in a "currently selected" date (`value`)
* It supports a `minDate`
* It has an `onChange` method that get called with the selected date on change (react-datepicker exposes an actual `Date` object instead of a formatted date, but either would meet our needs)

---

I don't know how beholden we are with keeping that exact styling of the calendar for the EventBar, so maybe EzCalendar is not the right solution. I thought that I'd float the idea since we're adding a new library with dependencies to get a calendar that we already have in recipe, and also so that we have a consistent a11y experience.

**Comment by noranda** [comment]
Closing this issue. Our roadmap includes a new component, `EzDatePicker`, that should solve this issue without exposing `EzCalendar`, as it would then be deprecated and removed. Stay tuned!
