### ISSUE TITLE
Bug: imagePosition prop does not have correct type for responsiveness

### ISSUE THREAD

**Issue by jbelang** [ezcater/recipe#509]
## Describe the bug

When attempting to use the responsive image positioning API on EzCard (with the same prop as the docs: 
```
imagePosition={{base: 'top', medium: 'left'}})
```
I get a TS error:
```
Type error: Type '{ base: string; medium: string; }' is not assignable to type 'Position'.
Type '{ base: string; medium: string; }' is not assignable to type '"left"'.
```
Looking at the source and comparing that to the EzLayout responsive layout API, it looks like EzLayout has a Responsive type that handles layout for it, while EzCard's Position is not expanded in such a way.

## Steps To Reproduce

1. Set an ezCard's `imagePosition` to `{{base: 'top', medium: 'left'}})`
2. Try to compile it, or run TS linting against it

Link to code example:

You can see a build failure here: https://jenkins.ezcater.net/blue/organizations/jenkins/ezcater-pipeline%2Fstore-next/detail/pjg%2Fsearch-results-skeleton/8/pipeline

## Current behavior
Using the props as described in the docs leads to code that TS won't compile.

## Expected behavior
Using the props as described in the docs leads to code that TS will compile.

## Screenshots
![image](https://user-images.githubusercontent.com/6944977/108543676-6094a980-72b3-11eb-80ec-d9ef33c2f500.png)

## Additional context
This is currently blocking progress on the search project.

**Comment by CraigCav** [comment]
This was fixed by #676.
