### ISSUE TITLE
Bug: `findByRole('radio')` appears to cause problems in testing

### ISSUE THREAD

**Issue by ez-alexfrazer** [ezcater/recipe#518]
## Describe the bug

Imagine I have a group of radios and I want to assert that one is selected. I might write a test like this:

https://user-images.githubusercontent.com/77698413/109662306-24b9d980-7b28-11eb-9054-820f9f15488b.mp4

I would expect to be able to write a test like this

```typescript
test('should change content when item is selected', async () => {
  render(<MyComponent />);

  expect(await screen.findByRole('radio', {name: /email/i})).toBeChecked();
  expect(await screen.findByRole('textbox', {name: /email/i})).toBeInTheDocument();
  expect(await screen.findByRole('textbox', {name: /phone/i})).not.toBeInTheDocument();

  userEvent.click(await screen.findByRole('radio', {name: /phone/i}));

  expect(await screen.findByRole('radio', {name: /phone/i})).toBeChecked();
  expect(await screen.findByRole('textbox', {name: /email/i})).not.toBeInTheDocument();
  expect(await screen.findByRole('textbox', {name: /phone/i})).toBeInTheDocument();
})
```

however, when I use this selector, I consistently get an error that the `parentElement` is null.

The current workaround is to use `screen.getByLabelText()`, which works, but I'd like to be able to use these selectors for more fine-grained access

## Steps To Reproduce

1. Write a test using a radio button or checkbox
2. Try using `screen.findByRole()` in various situations

Link to code example:

Note this one is a bit odd cause you gotta go to the `test` tab to see the problem

https://codesandbox.io/s/boring-goodall-eox4r?file=/src/App.test.tsx

## Current behavior
Throws an error

## Expected behavior

Should return the appropriate node

**Comment by noranda** [comment]
Closing this issue. This is no longer an issue using the most current dependency versions. https://codesandbox.io/s/dazzling-microservice-cibt2w?file=/src/App.test.tsx
