### ISSUE TITLE
EzPopover handles `escape` keypresses

### ISSUE THREAD

**Issue by evan-007** [ezcater/recipe#540]
**Is your feature request related to a problem? Please describe.**

We used EzPopover on the search page for the eventbar forms:

<img width="590" alt="Screen Shot 2021-03-18 at 1 35 53 PM" src="https://user-images.githubusercontent.com/5827130/111672857-c1e76400-87f0-11eb-8790-5b68a7ef3d0f.png">

Joe did an accessibility audit and reported that the `escape` key did not close the popover like he expected. It would be nice for keyboard users to have an easy way to close popovers that is part of the EzPopover itself so we don't have to setup eventlisteners ourselves todo this each time we use EzPopover.
 
**Describe the solution you'd like**

The [W3C docs](https://w3c.github.io/aria-practices) don't include specs for popovers from what i can see, but perhaps they should behave similar to modals or tooltips with regards to the escape key? I'm sure there are other things to consider, like what happens when the popover contains an input field that has focus when the escape key is pressed?

**Design Mockups**

N/A

**Comment by CraigCav** [comment]
EzPopover intentionally does not handle keypresses, as EzPopover is a low-level building block component used to build more complex interactions.
