### ISSUE TITLE
Export `FocusScope` or some other focus trapping utils

### ISSUE THREAD

**Issue by evan-007** [ezcater/recipe#556]
**Is your feature request related to a problem? Please describe.**

The search page in store-next uses EzPopover for its filters:

<img width="503" alt="Screen Shot 2021-03-31 at 9 46 03 AM" src="https://user-images.githubusercontent.com/5827130/113154450-04a03780-9206-11eb-85ba-d5e637124b5f.png">

In the old ez-rails version of the page, focus was trapped inside of the popover content so that pressing tab on the last item returned focus to the first item in the popover.

With the current Popover from recipe, focus is not trapped and focus is sent back to the document after the last popover content element. Related https://github.com/ezcater/recipe/issues/539

[slack thread](https://ezcater.slack.com/archives/CBC9DMGP5/p1617194660024000)

**Describe the solution you'd like**

Recipe has `FocusScope` which should help trap focus in the popover, but does not expose `FocusScope` as an export. Could/should recipe provide some focus utils? Or should recipe-consuming applications provide their own?

I can't think of another usecase for `FocusScope`.

Maybe related, I cannot get FocusScope to work with EzPopover https://codesandbox.io/s/nervous-babbage-ruioz?file=/src/App.js

Another solution could be a new prop to EzPopover like `containFocus: boolean` that traps focus in the popover. One potential issue for this would be if the popover did not provide a control in its content to close the popover, it could trap keyboard users inside.

**Design Mockups**

No changes

**Comment by CraigCav** [comment]
I think the behavior of EzPopover is working as designed - although we don't trap focus (and intentionally don't offer focus trapping as part of this component), focus does seem to be handled appropriately with respect to the trigger element. 

In the provided screenshot, I would expect tabbing from the `Halal` button into the dialog to work as expected, and subsequent tabs to iterate through the focusable items inside the popover. I would then expect the focus to be returned to the next focusable item _after the trigger_ when focus leaves the popover. 

In the following playroom [example](https://ezcater.github.io/recipe/playroom/?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgE4wBm2GASjAIZhUB0ArhTDYNkRXgBsxaANzFS5ahgDaANwCWFVQCMxMADQYBVAGrqtOgLrM2nHvxgBlKuyoxkDdmIHTZdGFV60JMg%2BpAA8UKrKBlQAnjpYwMAAFjCqAOZJVPAYAIwArAAMAL5FOCGkGKGqRAAOvFQA9GUkFWEAogBeAEL1VBBE5a12WAQgAuRQ7LQxo4MV9AwJC0VzpP0AwmKqYADWCejYeIYmGtquAIRqpzpoKy2ta0QA0jAxACIQAO5ECTCHGDBuDtXtgsFgMAByNoUMDsGowCEYABkSIMfhOZlc7k8MFuc2aDwqAHl4SQahBycoYLQ5qEGp0elQ%2BkRmnNgFdMcjUcF7g9Qp0AAoUiBU2gYJy0NJ%2BIRLRhFAxJCDiKCbCACIlELpiAIYDZiNUwfaYXBo4ymM5uDxeUqrCrhSK21rUOKGxKOh6aCC0WC0bIQigQLZQXI1AAeGCSFDE7GQBX0BQApPGkxgCtwAEx5NAQ3Tu1qe0P2JLsKBfP0FMMYdOVnIV8OR6Ox5PN1MZrM5vMVGoliJENLZdNxzukTScHZpWhKohQP0AYgYBQXC47vMJpBK7oJa6dUAYFF3naqtXqTU7FDPe4Pq7XR7qjS327pEWUD759I6Qsp1NfpDx19vJ4-pU1R3qe-4gYB5RPpEW7eEQRRoOgRQgEUQA) and screenshot, you can see the popover behaving as I would expect:
.

![Jul-21-2021 11-39-05](https://user-images.githubusercontent.com/109814/126517777-317ccab6-9503-4777-8a18-5398aad1090a.gif)


I'm going to go ahead and close this issue as "working-as-designed" but let me know if there are other use cases that crop up requiring a focus lock.
