### ISSUE TITLE
Bug: Recipe 12 + Marketplace Theme EzCards change dropshadow on hover

### ISSUE THREAD

**Issue by pgrippi** [ezcater/recipe#612]
## Describe the bug

The EzCards using the marketplace theme have a heavy dropshadow that changes to a thinner one on hover. I believe this is a regression in Recipe 12

## Screenshots

**Recipe 11**

https://user-images.githubusercontent.com/1180841/118033149-78ba1900-b336-11eb-923e-4fcda6104f04.mp4

**Recipe 12**

https://user-images.githubusercontent.com/1180841/118033135-75269200-b336-11eb-88de-ef07e9623554.mp4

**Comment by danidewitt** [comment]
fixed in https://github.com/ezcater/recipe/pull/816
