### ISSUE TITLE
Adjust padding from 24px to 32px on bottom of modal content

### ISSUE THREAD

**Issue by dave-ezcater** [ezcater/recipe#64]
Currently, the spacing below the last content item in a modal is 24px. I'd like it to be 32px to match the left and right edges.

![Screen Shot 2019-04-03 at 2 14 00 PM](https://user-images.githubusercontent.com/39057183/55502619-f91bd500-561a-11e9-8005-33da4900618d.png)

The current version's balance is slightly off.

**Comment by CraigCav** [comment]
I'm not sure our current designs necessarily align with this.
