### ISSUE TITLE
Support HTMLInputElement types in EzField

### ISSUE THREAD

**Issue by ez-alexfrazer** [ezcater/recipe#673]
## Steps To Reproduce

1. use `EzField` with `type="tel"`

Link to code example:

https://codesandbox.io/s/eloquent-goldwasser-y7uso?file=/src/App.tsx

## Current behavior

Shows a TS error, and renders the field very strangely

## Expected behavior

I'm seeing a discriminated union describing the type for `EzField`. If it conditionally renders an input, I would imagine that any valid `HTMLInputElement['type']` would be valid. I.e.,

```ts
type InputTypes = 'tel' | 'text' | 'email' | // ... etc.;
type ValidTypes = InputTypes | 'textarea' | 'autosuggest';

type InputType<TType extends ValidTypes = 'text'> = TType extends InputTypes ? Extract<HTMLInputElement, { type: TType }> : {
  type: 'textarea';
} | {
  type: 'autosuggest';
}
```

[Example here](https://www.typescriptlang.org/play?downlevelIteration=true&importHelpers=true&target=2&module=6&noErrorTruncation=true#code/JYWwDg9gTgLgBAbzgCQCoFkAyAFKEwDOcAvnAGZ4hwDkUApgIYDGM1A3AFAcwCeYdKDJgCSAOzABXGKj50iAXhpQGogOZ1qcAD40YdAB6ttuugBtNO6mWCmNx6nRAMb7brLhjJ02QsFZPUjL8RJYMUhAEEqrqBEaWeoYM9Ayubvwe4lK4+AQAPKhwBnqiACZEAd7BcIrUCawAfNVwBUV0pURo-pmVcnAA-H44eIS5nSLdAKK2IG0wjQBciBxwK3C8-Iu1RUmM1BykOgjLq+t0m2EwEVExrJzEnGkCAEJNFdkjVjYa9WxAA)

**Comment by CraigCav** [comment]
Recipe is unlikely going to support all variations of [input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types), as browser support for each varies considerably.

If you find a use case for a specific type, such as `tel`, we can create a specific issue for that feature and build out our implementation. The implementation may or may not leverage browser default behavior, depending on the designs and features we would be looking to support for the use case.

Recipe provides an escape hatch for applications to be able to build their own support for custom input types, allowing applications to experiment with and validate their needs while still having access to Recipe's default styling for text inputs. This feature is documented as a [Custom input field](https://ezcater.github.io/recipe/components/ez-field#custom-input-field) on the Recipe doc-site.

**Comment by CraigCav** [comment]
For reference, the TS error looks is as follows:

![`Type '"tel"' is not assignable to type '"number" | "select" | "textarea" | "time" | "text" | ComponentClass<any, any> | "radio" | "checkbox" | "email" | "password" | "date" | "autosuggest" | FC<any>'`](https://user-images.githubusercontent.com/109814/126331282-3534e102-332d-47b7-884e-e0cd7aa5212e.png)

At a glance, this appears correct; TypeScript is enumerating all the types that are valid for the EzField component today.
