### ISSUE TITLE
Enhancement: add `onClick` handlers to `EzCarousel`

### ISSUE THREAD

**Issue by morgannegagne** [ezcater/recipe#683]
The Store team has a had a few instances where we want to track a user's interaction with `EzCarousel`, specifically looking to track whether a user scrolls through the options. 

I'm not sure of the best naming, but it would be nice to have hooks into `onClickRight` and `onClickLeft` to see if a user clicks the right/left buttons to view different options.

**Comment by CraigCav** [comment]
Perhaps something like `onPageChange` might be a good option; the user can scroll through the options with other interactions besides a button press, like a two-finger swipe, or by tabbing through the carousel content (as might be the case with clickable cards).

I guess the implementation may depend on the level of granularity you need; are you interested in the interaction itself (i.e. distinguishing between clicks, swipes and tabs), or just whether the user is viewing the options beyond the first page? I suspect maybe the latter?

**Comment by morgannegagne** [comment]
Just whether the user is viewing options beyond the first page, which I hope simplifies things a bit. Thanks @CraigCav!
