### ISSUE TITLE
Documentation for how to access themes and ezCater colors

### ISSUE THREAD

**Issue by EliseFitz15** [ezcater/recipe#703]
**Is your feature request related to a problem? Please describe.**

I was looking for some direction and clarification on what best practice would be for accessing the recipe themes to leverage our ezCater colors and other styles. I seen multiple patterns through our frontend apps and wonder if this is something we can form an opinion around to make it more uniform moving forward. 
For example: 
```
import {themes} from '@ezcater/recipe';

export const CardContainer = styled.div`
  border: 1px solid ${themes.standard.colors.border.base};
  ...
```

in other repos something like this: 
const StyledIcon = styled(DeleteIcon)`
  align-self: flex-end;
  color: ${({theme}) => theme.colors.reds.base};
`;

**Describe the solution you'd like**

Request for documentation. More documentation and a formal opinion would help us move forward with a uniform approach. 

- When should this component be used?
- When shouldn’t it be used? For those cases, is there an alternative component you’d recommend (and why do you recommend it)?
- When should each variation of the component be used?
- What are guidelines for the content that could go into this component?
- Are there limitations/restrictions on what it can handle?
- Is anything not going into this first version? What did you exclude and what was the reasoning behind that?

**Design Mockups**

Add any other context and screenshots about the feature request here.

**Comment by danidewitt** [comment]
@EliseFitz15 thanks for creating an issue for this!

For clarification, are you trying to override the current recipe themes (either marketplace or fulfillment theme)?

**Comment by EliseFitz15** [comment]
Hi @danidewitt no not override themes on existing components but in the cases of leveraging the themes colors, fonts, spacing, etc. in other non-recipe components. For example here is a PR we create an circle element that changes colors based on percentage and wanted to use all the appropriate colors. https://github.com/ezcater/delivery-management-react/pull/928

**Comment by danidewitt** [comment]
@EliseFitz15 I understand now, thank you. 

I believe that delivery management repo is still on recipe 10, is that correct?

In version 11, we deprecated the standard theme for colors, spacing, and typography, and all of the existing corresponding documentation, see [here](https://ezcater.github.io/recipe/changelog#1100---2020-11-20) (in the documentation section) and [here](https://ezcater.github.io/recipe/changelog#1110---2020-12-16) (in the enhancements section). 

In version 12, we've removed the our usage of emotion in recipe and are actively helping downstream applications upgrade to the latest version. Please let us know if you and/or your team need support, we want to prioritize this!

**Comment by EliseFitz15** [comment]
Thanks @danidewitt that's great to know! I'll contact the owner of these repo and make sure it's on their radar for upgrading recipe. Just so I understand for the future, if I needed access to certain colors would I access them the Global Styles component?

**Comment by noranda** [comment]
Hi @EliseFitz15! We just released [Recipe v14](https://github.com/ezcater/recipe/releases/tag/v14.0.0) in PR https://github.com/ezcater/recipe/pull/803, which adds theming support! This includes [documentation](http://localhost:8000/guides/getting-started/#recipe-themes) about theming, describing how to extend themes and use theme properties like color in downstream apps (see below). A list of all our supported theme properties can be found on our new [Theming](http://localhost:8000/guides/theming) page.

```jsx
import {themes} from '@ezcater/recipe';
import {styled} from '@emotion/react';
const {ezTheme} = themes;

const MyComponent = styled.div`
  color: ${ezTheme.palette.common.primary100};
`;

// Also available as an emotion theme prop
const MyOtherComponent = styled.div`
  color: ${({theme}) => theme.palette.common.primary100};
`;
```
Hopefully this will be useful for you. Thanks for your issue!

**Comment by EliseFitz15** [comment]
Wooo! 🥇 🎆
