### ISSUE TITLE
Bug: EzCarousel does not gracefully handle asynchronously loaded data

### ISSUE THREAD

**Issue by ez-alexfrazer** [ezcater/recipe#727]
## Describe the bug

Here's the use case: I am asynchronously loading a series of items into the carousel of `n` total items. So every time I click the next or previous button, it would load the next page of results. Likely similar to a netflix like carousel.

https://user-images.githubusercontent.com/77698413/146215193-cc3eb196-d7ae-4d15-a3a9-9bd02e167785.mp4

#### Three ways of approaching this:

1. I could only load in the items that I need as the slides. [This doesn't work because the next button will not be available](https://ezcater.github.io/recipe/playroom/?code=N4Igxg9gJgpiBcIA8BRAXgYQIYCcIFcBnGAGwAJCSBLWQgBRhzqwHMYBeYAZgF8A%2BADoA7MmSR0SWMDAAWEErBxkA9IJFiJU2fMUq1o8ZOlyFjPcKTL02PEVJ8QPIA).

2. I could load in placeholders for all the unknown data, which is to say `0, offset` to the left and `max(offset + limit, totalCount), totalCount - 1` to the right. [while this does work, it causes that number of nodes to be added to the page, unbounded](https://ezcater.github.io/recipe/playroom/?code=N4Igxg9gJgpiBcIA8BRAXgYQIYCcIFcBnGAGwAJCSBLWQgBRhzqwHMYBeYAZgF8A%2BADoA7MmWABBHDiwBPAHQAzPAFsAFMDIkYQlgBcAFvDJcADGR4AaMqoD6VqkNgAPAJRl2fMkjoksYGPoQJLA4ZADWMDKcDs48ZAD0fC48wqISUrKKKuqa2nqGZACMZpbWdmQxMK7unt6%2B-oHBjOGR0Y5VZADUxiZxicmpYpLS8koQahpaOgZGAOwlVrb27dUeXj5%2BAUEhLVHAlU5dZAAsvQlJKUJI8ejYeESkfCA8QA)
![image](https://user-images.githubusercontent.com/77698413/146213791-4ae72e8d-e3f5-46b8-8052-aeecbc75c6e0.png)

^ this had one hundred `HTMLLIElement`s rendered underneath, so it's no bueno for an unbounded data set size.

3. I could load one buffer of size `limit` to the left and to the right, but this goes into territory where I feel like it needs to be better documented as a use case. [This did seem to work, though it is a bit of an unusual implementation that can be unclear to other developers without thorough documentation](https://ezcater.github.io/recipe/playroom/?code=N4Igxg9gJgpiBcIA8BRAXgYQIYCcIFcBnGAGwAJCSBLWQgBRhzqwHMYBeYAZgF8A%2BADoA7MmWABBHDiwBPAHQAzPAFsAFMDIkYQlgBcAFvDIBGAAxkeAGjKqA%2BtapDYADwCUZdnzJI6JLGBh9CBJYHDIAaxgZTkcXHjIAej5XHmFRCSlZRRV1TW09QxNzKxt7MliYNw8vHz8AoJDGCKiYp0qyAGoi%2BKSUtLFJaXklCDUNLR0DIzMLazsHNqrPb19-QODQ5ujgCudOsgAmUx7k1KEkBPRsPCJSPhAeIA)

## Steps To Reproduce

Simply load in a Carousel with n number of placeholders to see

Link to code example:

## Current behavior

Effectively, it will just load as many items as it can into the box

## Expected behavior

I think there's two possible ways to approach this:

1. Windowing content. Effectively, render only the content that is visible in the viewport, then a buffer to the left and right for when they click the buttons.
2. Provide controls for `totalCount`, `hasNext`, `hasPrevious`, `currentPage`, etc as unidirectional props then just does some sleight of hand to only render a left buffer, current items, and right buffer
3. Possibly just document a good strategy for working with asynchronously loaded, paginated collections? My third strategy seemed fairly effective, but it definitely wasn't the easiest to figure out

Here's a small example featuring windowing content:

https://codesandbox.io/s/staging-worker-co7th?file=/src/App.tsx

**Comment by noranda** [comment]
@ez-alexfrazer There are some interesting ideas here for handling carousels with _n_ number of items, although we currently do not support this in `EzCarousel`. As a best practice, carousels should have a set number of items that make sense for its context. A user will only navigate so far into a carousel, so creating one with _n_ number of items removes this construct and could potentially create a poor user experience.

That said, we are working on reworking `EzCarousel` and will be sure to look at performance as part of this. Thanks for your suggestions!
