### ISSUE TITLE
Bug: EzCard strange behavior in chrome

### ISSUE THREAD

**Issue by evan-007** [ezcater/recipe#754]
## Describe the bug

A list of EzCard's inside of a scrolling flexbox container w/`vh: 100` will sometimes not render elements correctly.

## Steps To Reproduce

1. https://codesandbox.io/s/exciting-kalam-73nut?file=/src/App.tsx view as fullscreen in a new window in chrome: https://73nut.csb.app/
2. scroll to the top, then bottom of the screen, notice elements someimtes don't render
3. you may need to hover on some of the cards before scrolling
4. Cards will render correctly on hover:

https://user-images.githubusercontent.com/5827130/152193618-e14e9025-ed13-426b-a4a6-d286705da67a.mov

Link to code example:

https://codesandbox.io/s/exciting-kalam-73nut?file=/src/App.tsx

## Current behavior

not all items render correctly

## Expected behavior

Items render in chrome like they do in other browsers

## Screenshots

https://user-images.githubusercontent.com/5827130/152193618-e14e9025-ed13-426b-a4a6-d286705da67a.mov

## Additional context

This seems to only happen when inside of a flexbox container that scrolls. If the page scrolls naturally, there's no issue.

**Comment by onocy** [comment]
At this time, this issue seems to be remediated with newer versions of chrome (98- current stable) and 99/100 (available through canary/beta). 

I'm closing out this issue as we will be waiting for users to migrate over to the newest chrome version across time to remediate this rendering issue.
