### ISSUE TITLE
Update visual regression tests to trim screenshots to support testing larger screens.

### ISSUE THREAD

**Issue by neogeek** [ezcater/recipe#98]
Update visual regression tests to trim screenshots to support testing larger screens.

Update visual regression tests (via sosia) to trim screenshots to support testing larger screens.

```
new PuppeteerBrowserTarget({
	width: 1024,
	height: 768,,
	trim: true
})
```

A [recommendation](https://github.com/americanexpress/jest-image-snapshot/issues/83#issuecomment-397840357) in the issues of [`jest-image-snapshot`](https://github.com/americanexpress/jest-image-snapshot) is to use the `autocrop` feature of the [jimp](https://github.com/oliver-moran/jimp) library.

<https://github.com/oliver-moran/jimp/blob/85c02cead6b2b5f1bb9836fb9ce6a2cff209d66b/packages/plugin-crop/README.md>

```javascript
import jimp from 'jimp';

async function main() {
  const image = await jimp.read('test/image.png');

  image.autocrop();
  image.autocrop({ cropOnlyFrames: false, cropSymmetric: true });
}

main();
```

**Comment by CraigCav** [comment]
This change would be part of Sosia rather than Recipe.
